SET
search_path TO logistics, public;

CREATE TABLE location
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(150),
    address_line VARCHAR(250),
    city         VARCHAR(120),
    country      VARCHAR(60),
    postal_code  VARCHAR(20),
    latitude     DOUBLE PRECISION,
    longitude    DOUBLE PRECISION
);
COMMENT
ON TABLE location IS 'Tek adres/koordinat defteri';
