SET
search_path TO logistics, public;

CREATE TABLE orders
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    special_notes TEXT
);

CREATE TABLE order_item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT  NOT NULL,
    description  TEXT,
    weight_kg    NUMERIC(12, 3),
    volume_m3    NUMERIC(12, 3),
    hazard_flag  BOOLEAN NOT NULL DEFAULT FALSE,
    temp_control BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_order_item__order FOREIGN KEY (order_id) REFERENCES orders (id)
);
CREATE INDEX idx_order_item__order_id ON order_item (order_id);

CREATE TABLE order_stop
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT    NOT NULL,
    role         stop_role NOT NULL,
    location_id  BIGINT    NOT NULL,
    window_start TIMESTAMPTZ,
    window_end   TIMESTAMPTZ,
    seq          INT,
    CONSTRAINT fk_order_stop__order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_stop__location FOREIGN KEY (location_id) REFERENCES location (id)
);
CREATE INDEX idx_order_stop__order_id ON order_stop (order_id);
CREATE INDEX idx_order_stop__location_id ON order_stop (location_id);
CREATE UNIQUE INDEX uq_order_stop__order_role_seq ON order_stop (order_id, role, seq);

CREATE TABLE order_party
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT    NOT NULL,
    role       role_type NOT NULL,
    party_name VARCHAR(150),
    CONSTRAINT fk_order_party__order FOREIGN KEY (order_id) REFERENCES orders (id)
);
CREATE INDEX idx_order_party__order_id ON order_party (order_id);
