SET
search_path TO logistics, public;

CREATE TABLE consignment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT
ON TABLE consignment IS 'Fiziksel parça (palet/koli/ton) — split/konsolidasyon için';

CREATE TABLE consignment_item
(
    consignment_id BIGINT NOT NULL,
    order_item_id  BIGINT NOT NULL,
    weight_kg      NUMERIC(12, 3),
    volume_m3      NUMERIC(12, 3),
    CONSTRAINT pk_consignment_item PRIMARY KEY (consignment_id, order_item_id),
    CONSTRAINT fk_cons_item__consignment FOREIGN KEY (consignment_id) REFERENCES consignment (id),
    CONSTRAINT fk_cons_item__order_item FOREIGN KEY (order_item_id) REFERENCES order_item (id)
);
CREATE INDEX idx_cons_item__consignment_id ON consignment_item (consignment_id);
CREATE INDEX idx_cons_item__order_item_id ON consignment_item (order_item_id);
