SET
search_path TO logistics, public;

CREATE TABLE shipment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    reference_no VARCHAR(80)
);
COMMENT
ON TABLE shipment IS 'Planlanan taşıma (genel başlık)';

CREATE TABLE shipment_consignment
(
    shipment_id    BIGINT NOT NULL,
    consignment_id BIGINT NOT NULL,
    CONSTRAINT pk_shipment_consignment PRIMARY KEY (shipment_id, consignment_id),
    CONSTRAINT fk_ship_cons__shipment FOREIGN KEY (shipment_id) REFERENCES shipment (id),
    CONSTRAINT fk_ship_cons__consignment FOREIGN KEY (consignment_id) REFERENCES consignment (id)
);
CREATE INDEX idx_ship_cons__shipment_id ON shipment_consignment (shipment_id);
CREATE INDEX idx_ship_cons__consignment_id ON shipment_consignment (consignment_id);

CREATE TABLE carrier
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    contact     VARCHAR(150),
    location_id BIGINT,
    CONSTRAINT fk_carrier__location FOREIGN KEY (location_id) REFERENCES location (id)
);
CREATE INDEX idx_carrier__location_id ON carrier (location_id);
COMMENT
ON TABLE carrier IS 'Dış taşıyıcı: airline, liner, 3PL, alt kara taşıyıcı vb.';

CREATE TABLE vehicle
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number  VARCHAR(20) UNIQUE,
    capacity_kg   NUMERIC(12, 3),
    capacity_m3   NUMERIC(12, 3),
    pallet_cap    INT,
    adr_compliant BOOLEAN NOT NULL DEFAULT FALSE,
    cold_chain    BOOLEAN NOT NULL DEFAULT FALSE
);
COMMENT
ON TABLE vehicle IS 'Kendi karayolu filomuz için';

CREATE TABLE driver
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  VARCHAR(120) NOT NULL,
    license_no VARCHAR(50),
    phone      VARCHAR(20)
);

CREATE TABLE shipment_leg
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id       BIGINT NOT NULL,
    seq               INT    NOT NULL,
    mode              mode   NOT NULL,
    vehicle_id        BIGINT,
    driver_id         BIGINT,
    carrier_id        BIGINT,
    booking_ref       VARCHAR(80),
    awb_no            VARCHAR(50),
    bl_no             VARCHAR(50),
    cmr_no            VARCHAR(50),
    start_location_id BIGINT NOT NULL,
    end_location_id   BIGINT NOT NULL,
    planned_start     TIMESTAMPTZ,
    planned_end       TIMESTAMPTZ,
    actual_start      TIMESTAMPTZ,
    actual_end        TIMESTAMPTZ,
    CONSTRAINT fk_leg__shipment FOREIGN KEY (shipment_id) REFERENCES shipment (id),
    CONSTRAINT fk_leg__start_location FOREIGN KEY (start_location_id) REFERENCES location (id),
    CONSTRAINT fk_leg__end_location FOREIGN KEY (end_location_id) REFERENCES location (id),
    CONSTRAINT fk_leg__vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicle (id),
    CONSTRAINT fk_leg__driver FOREIGN KEY (driver_id) REFERENCES driver (id),
    CONSTRAINT fk_leg__carrier FOREIGN KEY (carrier_id) REFERENCES carrier (id)
);
CREATE INDEX idx_leg__shipment_id ON shipment_leg (shipment_id);
CREATE UNIQUE INDEX uq_leg__shipment_seq ON shipment_leg (shipment_id, seq);
CREATE INDEX idx_leg__start_loc ON shipment_leg (start_location_id);
CREATE INDEX idx_leg__end_loc ON shipment_leg (end_location_id);
CREATE INDEX idx_leg__vehicle ON shipment_leg (vehicle_id);
CREATE INDEX idx_leg__driver ON shipment_leg (driver_id);
CREATE INDEX idx_leg__carrier ON shipment_leg (carrier_id);
CREATE INDEX idx_leg__shipment_planned_start ON shipment_leg (shipment_id, planned_start);
COMMENT
ON TABLE shipment_leg IS 'Mode’a göre ya vehicle/driver (kendi ROAD) ya da carrier+booking (AIR/SEA/dış ROAD) kullanılır';
