SET
search_path TO logistics, public;

CREATE TABLE status_event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type entity_type NOT NULL,
    entity_id   BIGINT      NOT NULL,
    status      VARCHAR(60),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    note        TEXT
);
CREATE INDEX idx_status_event__etype_eid_time
    ON status_event (entity_type, entity_id, occurred_at);

CREATE TABLE document
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type     VARCHAR(60),
    file_url     TEXT,
    related_type entity_type,
    related_id   BIGINT,
    uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_document__rtype_rid_time
    ON document (related_type, related_id, uploaded_at);
