name: logistics
services:
  db:
    image: postgres:17
    container_name: logistics-db
    ports: ["55432:5432"]               # host:container
    env_file: .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 3s
      retries: 20

  flyway:
    image: flyway/flyway:10
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - ../src/main/resources/db/migration:/flyway/sql
    command: >
      -url=jdbc:postgresql://db:5432/${PGDATABASE}
      -user=${FLYWAY_USER}
      -password=${FLYWAY_PASSWORD}
      -schemas=${PGSCHEMA}
      -defaultSchema=${PGSCHEMA}
      -connectRetries=60
      migrate

volumes:
  pgdata:
